language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  - composer create-project --prefer-source --dev --no-interaction zenify/ci vendor/ci @dev
  - . vendor/ci/travis/coverage-init.sh
  - composer update --prefer-source $PREFER_LOWEST

before_script:
  - . vendor/ci/travis/static-analysis.sh

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - . vendor/ci/travis/coverage-send.sh
